### check server status
GET http://localhost:8000/



#========Admin API
###post new admin user
POST http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
    
    "fName":"Anmolsssg",
    "lName": "Bhatstasrasig",
    "email": "anmol.bhattarai1945@gmail.com",
    "password": "123456",
    "phone": "0980754421",
    "address": "queansby",
    "DOB": ""
}


###Login using admin email/password
POST http://localhost:8000/api/v1/admin-user/login
Content-Type: application/json

{
    "email": "anmol.bhattarai1944@gmail.com",
    "password": "123456"
}



