### check server status
GET http://localhost:8000/



#========Admin API
###post new admin user
POST http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
    "fName": "Anmolg",
    "lName": "Bhattaraig",
    "email": "ay@a",
    "password": "aaggf",
    "phone": "0987754321",
    "address": "queanbey",
    "DOB": "1995-01-17"

}



